name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@v0.1.7

        with:
          host: ${{ secrets.SSH_HOST }}
          ssh-key-key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          script_stop: true
          
          script: |

            cd /var/www/test-ci-cd/test-ci-cd/

            git checkout -f

            git pull origin main


